default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: equus_hub_development

test:
  <<: *default
  database: equus_hub_test

production:
  password: <%= ENV['DATABASE_URL'] %>
