default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: postgres
  password: 12345678
  database: backend_development

# test:
#   <<: *default
#   database: test

# production:
#   password: <%= ENV['DATABASE_URL'] %>